const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';
const APP_INIT='APP_INIT';
const APP_LOGIN='APP_LOGIN';
const APP_START_APP='APP_START_APP';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,
    APP_INIT,
    APP_LOGIN,
    APP_START_APP
}