const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';
const APP_INIT = 'APP_INIT';
const APP_INIT_CAN_SCROLL = 'APP_INIT_CAN_SCROLL';
const APP_LOGIN = 'APP_LOGIN';
const APP_START_APP = 'APP_START_APP';
const LOGIN_USER_INFO_INIT = 'LOGIN_USER_INFO_INIT';
const LOGOUT_USER_INFO_CLEAR = 'LOGOUT_USER_INFO_CLEAR';
const USER_UNSAFE_UPDATE = 'USER_UNSAFE_UPDATE';
const ACCELERATE_TYPE_CHANGE = 'ACCELERATE_TYPE_CHANGE';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,
    APP_INIT,
    APP_INIT_CAN_SCROLL,
    APP_LOGIN,
    APP_START_APP,
    LOGIN_USER_INFO_INIT,
    LOGOUT_USER_INFO_CLEAR,
    USER_UNSAFE_UPDATE,
    ACCELERATE_TYPE_CHANGE
}