/** 
 * Pages`name constant registry 
 * 
 * Navigation`s helper document. Searching the page by this registry to check the correctness of the page name.
 * 
 * creat by Charlie on 2019-08-19
*/

export default {
    BOTM_TAB: 'BOTM_TAB',
    BOTM_TAB_FIRST: 'BOTM_TAB_FIRST',
    BOTM_TAB_SECOND: 'BOTM_TAB_SECOND',
    BOTM_TAB_THIRD: 'BOTM_TAB_THIRD',
    BOTM_TAB_FOURTH: 'BOTM_TAB_FOURTH',

    NORMAL_STACK: 'NORMAL_STACK',
    NORMAL_STACK_PUSH: 'NORMAL_STACK_PUSH',
    NORMAL_STACK_BRIDGE: 'NORMAL_STACK_BRIDGE',
    NORMAL_STACK_NETWORK: 'NORMAL_STACK_NETWORK',
    NORMAL_STACK_TOAST: 'NORMAL_STACK_TOAST',
    NORMAL_STACK_FLATLIST: 'NORMAL_STACK_FLATLIST',
    NORMAL_PROGRESS_RATE: 'NORMAL_PROGRESS_RATE',
    NORMAL_PERSONAL_INFO: 'NORMAL_PERSONAL_INFO',
    NORMAL_CHANGE_PHONE_NUM: 'NORMAL_CHANGE_PHONE_NUM',
    NORMAL_CHANGE_NICK_NAME: 'NORMAL_CHANGE_NICK_NAME',
    NORMAL_ABOUT_US: 'NORMAL_ABOUT_US',
    NORMAL_NOTICE: "NORMAL_NOTICE",
    NORAML_LOGIN_PAGE: 'NORAML_LOGIN_PAGE',
    ACCELERATE_DETAILS_PAGE: 'ACCELERATE_DETAILS_PAGE',


    NORMAL_PAGE_ACCELERATOR: 'NORMAL_PAGE_ACCELERATOR',
    NORMAL_PAGE_SETTING: 'NORMAL_PAGE_SETTING',
    NORMAL_PAGE_SUGGESTION: 'NORMAL_PAGE_SUGGESTION',
    NORMAL_PAGE_SEARCH: 'NORMAL_PAGE_SEARCH',

    NORMAL_PAGE_GAME_HOME_PAGE: 'NORMAL_PAGE_GAME_HOME_PAGE',
    NORMAL_PAGE_MINE:'NORMAL_PAGE_MINE',

    MODAL_WRAPPER: 'MODAL_WRAPPER',
    MODAL_ALERT: 'MODAL_ALERT',
    MODAL_ALERT_BOTTOM: 'MODAL_ALERT_BOTTOM'
}