/** 
 * Pages`name constant registry 
 * 
 * Navigation`s helper document. Searching the page by this registry to check the correctness of the page name.
 * 
 * creat by Charlie on 2019-08-19
*/

export default {
    BOTM_TAB: 'BOTM_TAB',
    BOTM_TAB_FIRST: 'BOTM_TAB_FIRST',
    BOTM_TAB_SECOND: 'BOTM_TAB_SECOND',
    BOTM_TAB_THIRD: 'BOTM_TAB_THIRD',
    BOTM_TAB_FOURTH: 'BOTM_TAB_FOURTH',

    NORMAL_STACK: 'NORMAL_STACK',
    NORMAL_STACK_PUSH: 'NORMAL_STACK_PUSH',
    NORMAL_STACK_BRIDGE: 'NORMAL_STACK_BRIDGE',
    NORMAL_STACK_NETWORK: 'NORMAL_STACK_NETWORK',
    NORMAL_STACK_TOAST: 'NORMAL_STACK_TOAST',
    NORMAL_STACK_FLATLIST: 'NORMAL_STACK_FLATLIST',
    NORMAL_PROGRESS_RATE: 'NORMAL_PROGRESS_RATE',
    NORMAL_CHANGE_PHONE_NUM: 'NORMAL_CHANGE_PHONE_NUM',
    NORMAL_CHANGE_NICK_NAME: 'NORMAL_CHANGE_NICK_NAME',
    NORMAL_LOGIN: 'NORMAL_LOGIN',

    MODAL_WRAPPER: 'MODAL_WRAPPER',
}